### ISSUE TITLE
Linking the next topic in docs to maintain ease of flow to readers

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [The-Taggart-Institute/creating-with-git#4]
Hello @mttaggart,

I was reading the docs for Git, (getting acquainted, merging, fixing errors, etc. topics). I could see that you have mentioned the name of the topic you will be having a documentation of.

My suggestion is that what if I could add a link of the next topic being mentioned in markdown. So that if someone wants to read more, he/she can just click on it and automatically get redirected to the respective page instead of going back, clicking the next .md file and open it again.

It will make the repo maintain a streamlined flow for ones who are new to this repo.

I want to know to know your thoughts on this. 

Please give me a heads up, I will make the changes, and will review with you if so. 
If you want to have more clarity, please ask them.

Thank you.

**Comment by ShubhamJagtap2000** [comment]
Hello @mttaggart, would you please address my issue?

**Comment by mttaggart** [comment]
Hi! I don't really consider this an issue, as "reading it on GitHub" is not the intended viewing of the material.

A quick glance over at the Deployments would reveal a GitHub Pages instance.

![image](https://github.com/The-Taggart-Institute/creating-with-git/assets/6811816/1c0e1010-ed77-4cd0-81da-34b47a2f78ca)

As the repo is intended to work with the course material, and the course material links people to our free online text at https://cwg.taggartinstitute.org, which _does_ have previous/next navigation, I'm going to consider this matter closed.
